### ISSUE TITLE
Kirby won't load in browser

### ISSUE THREAD

**Issue by lipcanu** [NECKRHINOS/kirby-bootstrap-starterkit#1]
Hi @NECKRHINOS, thanks so much for making this, it seems a super useful starterkit. However, I've been trying for quite a while to make it run, but I'm not sure what's wrong, as localhost:3001 runs just fine, while localhost:3000 where the kirby should be won't load, with no console errors or npm errors, so I can't tell what's wrong :) thanks a bunch :)

**Comment by dorb4n** [comment]
@lipcanu do you have php installed?

Can you run _php -S localhost:8000_ from the root folder?

**Comment by NECKRHINOS** [comment]
What @dorb4n said. Sorry for the late feedback @lipcanu I've just cloned and run the repository and both running the site from the Gulp file (_localhost:3000_, _:3001_, _:3002_ etc.) as running the site by manually typing the command _php -S localhost:8000_ work fine for me.
